[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
fs_permissions = [{ access = "read", path = "./"}]
remappings = [
    "@solmate-utils/=lib/solmate/src/utils/",
    "@prb/math/=lib/prb-math/"
]
